name: Linty
on:
  push:
  pull_request:

jobs:
  build:
    name: Linty
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      LINTY_YOSYS_PLUGIN_VERSION: 0.15.0

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Install Tabby CAD Suite
        run: |
          cd /opt
          pip install gdown
          gdown https://drive.google.com/file/d/11owYZ8XqArHr9OVEGQjtyfOEY6W-EqUZ/view?usp=sharing --fuzzy
          tar xfz tabby-linux-x64-latest.tgz
          cd tabby
          mkdir ./share/yosys/plugins
          echo "$TABBY_CAD_LICENSE" >> license.txt
        env:
          TABBY_CAD_LICENSE: ${{secrets.TABBY_CAD_LICENSE}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Linty Yosys Plugin
        uses: dsaltares/fetch-gh-release-asset@1.1.0
        with:
          repo: "Linty-Services/linty-yosys-plugin"
          version: "tags/${{env.LINTY_YOSYS_PLUGIN_VERSION}}"
          file: "linty-yosys-plugin-${{env.LINTY_YOSYS_PLUGIN_VERSION}}.tar.gz"
          target: "linty-yosys-plugin-${{env.LINTY_YOSYS_PLUGIN_VERSION}}.tar.gz"
          token: ${{ secrets.PUBLIC_SHARE_GITHUB_TOKEN }}

      - name: Install Linty Yosys Plugin
        run: tar -xvzf linty-yosys-plugin-${{env.LINTY_YOSYS_PLUGIN_VERSION}}.tar.gz -C /opt/tabby/share/yosys/plugins

      - name: Run Linty
        run: |
          export TABBY_CAD_HOME=/opt/tabby
          export PATH="$TABBY_CAD_HOME/bin:$PATH"
          export YOSYSHQ_LICENSE=/opt/tabby/license.txt
          wget -q https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856.zip
          unzip -q sonar-scanner-cli-4.8.0.2856.zip
          ./sonar-scanner-4.8.0.2856/bin/sonar-scanner \
            -Dsonar.host.url=https://sonar.linty-services.com \
            -Dsonar.login=${{ secrets.SONARQUBE_SCANNER_FOR_PRIVATE_REPOSITORIES_TOKEN }} \
            -Dsonar.projectKey=sefuw-demo \
            -Dsonar.projectName="SEFUW Demo" \
            -Dsonar.sources=. \
            -Dsonar.vhdl.topLevelEntity=sleep
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: debug
          path: |
            bugfinder_workdir/